import { CalendarDays, Mail, PanelsTopLeft, Sparkles, ArrowUpRight } from 'lucide-react';
import { CTA, Eyebrow, SectionTitle } from '../components/UI';
export default function EightAM(){return <>
<section className="product-hero"><div><Eyebrow>BlueForge 8AM · Prepare</Eyebrow><h1>Your organization, summarized <em>before coffee.</em></h1><p>A personalized, actionable morning brief generated from the systems where your work already happens.</p><div className="button-row"><CTA to="/contact">Join early access</CTA><a className="text-link" href="#experience">See the experience ↓</a></div></div><div className="sun-visual"><div className="sun-disc"/><div className="horizon"/><span>08:00</span></div></section>
<section className="section" id="experience"><SectionTitle eyebrow="The experience" title="Less searching. Less asking. More knowing." copy="8AM gathers the signals, connects the context, and tells you what matters now." />
<div className="feature-trio"><div><CalendarDays/><h3>What changed</h3><p>Important updates since your last brief, without the noise.</p></div><div><Sparkles/><h3>What matters</h3><p>Priorities ranked by urgency, impact, and your preferences.</p></div><div><PanelsTopLeft/><h3>What to do next</h3><p>Clear recommendations with direct links back to the source.</p></div></div></section>
<section className="section connector-section"><div><Eyebrow>V1 connectors</Eyebrow><h2>A focused first version.</h2><p>BlueForge 8AM V1 connects monday.com, Gmail, and Google Calendar to produce a useful daily brief—without pretending to support every system on day one.</p></div><div className="connector-cards"><div><PanelsTopLeft/><strong>monday.com</strong><span>Tasks · deadlines · blockers</span></div><div><Mail/><strong>Gmail</strong><span>Important messages · follow-ups</span></div><div><CalendarDays/><strong>Google Calendar</strong><span>Meetings · conflicts · preparation</span></div></div></section>
<section className="section final-cta"><div><Eyebrow>Early access</Eyebrow><h2>Help shape the first version of 8AM.</h2></div><CTA to="/contact">Join the list</CTA></section>
</>}
